version: '3.9'



# docker-compose -f docker-compose.dev.yml build
# docker-compose -f docker-compose.dev.yml up -d

services:
  app:
    build: ./app
    container_name: flask_app
    command: gunicorn --bind 0.0.0.0:5000 app:app
    environment: 
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: unless-stopped
  

    volumes:
      - pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432
  
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.postgresql
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5555

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static:/home/web/default/static
    depends_on:
      - db
      # - pgadmin

volumes:
  pg_db:
  static: